# Generated by Django 4.1.1 on 2022-09-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_myobject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyObject',
        ),
    ]
